### ISSUE TITLE
Compatability without simple_form

### ISSUE THREAD

**Issue by variousred** [arvindvyas/Country-State-Select#33]
I want to use this gem without having to use `simple_form`.
I already have an established app with many forms that i need to add this country/state functionality to.

**Comment by variousred** [comment]
This is a workaround
```
              <% options = { form: f, field_names: { :country => :country, :state => :state} } %>
              <%= f.select :state, CountryStateSelect.state_options(options)[:collection], class: "form-control", required: true %>
```

**Comment by arvindvyas** [comment]
You can use older version of it , I am trying to manage it separately.

**Comment by aldefouw** [comment]
@variousred 

When I wrote this gem for Version 3.0, I completely changed the public interface that @arvindvyas had in Version 2.0.  I wrote it with simple_form in mind because the application that I was working on used simple_form.  

I improved it, but I added dependencies, which is bad - I apologize.

I have simple_form listed as a dependency in the gemspec, but I should really change that.

**The good news is, according to my testing, simple_form is unnecessary.  **

This gem should work with plain old "form_for" form objects as well.

I just ran a test on code like this.

`<%= form_for @form_object do |f| %>
    <%= f.select :work_country, CountryStateSelect.countries_collection %>
    <%= f.select :work_state, CountryStateSelect.state_options(label: "State / Province", form: f, field_names: {:country => :work_country, :state => :work_state}) %>
<% end %>`

It worked for me.

I need to do some more testing and make sure this is the case and there aren't any hidden problems I neglected to observe - but if I were you, I would give it a try and see if it works for you.

If I can prove that this works without simple_form, I will issue a new version that removes the simple_form dependency and update the documentation accordingly.

Give it a try without simple_form, but stay tuned ...

**Comment by variousred** [comment]
Thanks for that update, @aldefouw , sounds good

**Comment by aldefouw** [comment]
**UPDATE**

I am working on a version that should support form_for, but as I work on it, I am realizing that there are some serious bugs related to cities implementation.  I'll haven't reviewed that code that was added so I'll have to talk with Arvind about them.

What that means for you is that whatever I deliver to you will have broken cities implementation.  Is that a problem?

In any case, the form_for implementation will end up being like this:
'
<%= form_for @location do |f| %>

    <p>Country</p>
    <%= f.select :test_country, CountryStateSelect.countries_collection, selected: f.object.test_country %>

    <p>State / Province</p>
    <%= f.select :test_state, CountryStateSelect.collect_states(f.object.test_country), selected: f.object.test_state %>

    <p>City</p>
    <%= f.select :test_city, CountryStateSelect.collect_cities(f.object.test_country, f.object.test_state), selected: f.object.test_city %>

    <br /><br />

    <%= f.button "Submit", class: "btn btn-success" %>

    <%= link_to "Cancel", locations_path, class: "btn btn-danger" %>

<% end %>'

Part of the goal of requiring simple form is that things are passed with hashes, so you don't need to manually specify that you have a particular item specified in a list.  It just works.

Using simple_form, the gem protects users from having the headache of remembering to select their value.  Since a lot of people use partials for their forms, this seemed like a good route.  

There's also some difficulties related to if you want to return a string versus a list in form_for.  Simple form facilitated some pretty complex things without writing a ton of code. 

I can understand wanting form_for to work though - I get it that legacy code needs to be supported.

It will be more code no matter what I do, however. 

With form_for, you'll have to manually specify what is selected.  There isn't much I can do to get around that, unless you'd prefer just passing a form object into a method that you place inside the form_for block.

The problem I have with that is that it becomes so abstract to someone reading the form what is actually happening then.

**Comment by aldefouw** [comment]
I will be posting updates to this branch:

https://github.com/aldefouw/Country-State-Select/tree/regular_form_attempt

I am not done with it, but it's a start.

**Comment by arvindvyas** [comment]
@aldefouw  which code is breaking for cities ?

**Comment by aldefouw** [comment]
@arvindvyas 

I'll need to look at it again tonight since I am currently at my "day job," but as I recall from my testing, cities are not re-populated correctly for edit forms once you have selected them initially.

I will verify tonight unless you want to do your own testing.

https://github.com/aldefouw/Country-State-Select/tree/regular_form_attempt

You can probably see the behavior manifested in the /edit/ page I added to the demo of the branch I was working on for @variousred.

**Comment by arvindvyas** [comment]
@variousred  if you use  form like `<%= form_for @location do |f| %>
  <%= f.select :test_country,  CountryStateSelect.countries_collection %>
  <%= f.select :test_state,  []	 %>
  <%= f.select :test_city,  []	 %>
 <%end%>`

this will work 

In the next version of country_state_select simple form will be removed as an dependency

**Comment by aldefouw** [comment]
@arvindvyas - I agree that the code you are showing technically works for a #new action.  

I would caution you though; remember that some people will need a way to reload the data they've already submitted for the #edit action.

They could use a different form for the edit action and load things appropriately, it's true - but many people use a form partial for their #new and #edit forms, and it's painful to have to create separate forms.

The ideal thing would be to create an abstracted method that could be called on a common form partial that would take care of all of the messy logic that determines the appropriate data to be loaded.

I am not sure of the cleanest way to do it, but that's my two cents anyway.

**Comment by variousred** [comment]
Thanks for your work on this, guys

**Comment by arvindvyas** [comment]
@aldefouw you are right, this is a temporary solution for those who want to use form for not simple form , I have also removed simple_form from the dependencies so that people who really want to use simple form can add gem inside their application .  I will look into the form_for for edit now and once it will complete will do new release.

**Comment by aldefouw** [comment]
Sounds good, @arvindvyas.  I understand where you are coming from.
